# Homework 2

## Question2: Handwriting Recognition Using ANN:

In [1]:
# Importing libraries and packages:

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import metrics

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn import metrics
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

### a- Download the dataset "Digit". Check out the dataset

#### Set up Feature Matrix and Label Vector

In [2]:
# "read_csv" is a pandas function to read csv files from web or local device:

digit_df = pd.read_csv('https://raw.githubusercontent.com/ellipsclamation/cs5661_data_science/master/Datasets/label.csv')

# checking the dataset by printing 15 lines:
digit_df.head(15)

name of the file  digit
0                  0      0
1                  1      1
2                  2      2
3                  3      3
4                  4      4
5                  5      5
6                  6      6
7                  7      7
8                  8      8
9                  9      9
10                10      0
11                11      1
12                12      2
13                13      3
14                14      4

### b- Build the feature matrix and label vector:
Each image is considered as a data sample with pixels as features.
Thus, to build the feature table you have to convert each 8x8 image
into a row of the feature matrix with 64 feature columns for 64 pixels.

In [3]:
# Create a numpy array with values of each pixel from images as features
path = '.\\Datasets\\Digit\\'

feature_matrix = []

for filename in digit_df['name of the file']:
    image = mpimg.imread(path + str(filename) + '.jpg')
    feature_matrix.append(image.flatten())
    
feature_matrix = np.asarray(feature_matrix)
print(feature_matrix.shape)

(1797, 64)


Add feature matrix and label vector to dataframe

In [4]:
# Add feature matrix and label vector to dataframe
digit_df = digit_df.join(pd.DataFrame(feature_matrix))

# Re-organize dataframe
cols = list(digit_df.columns.values)
cols.append(cols.pop(1))
digit_df = digit_df[cols]

print(digit_df.head())

   name of the file  0  1    2    3    4    5   6  7   8  ...    55  56  57  \
0                 0  0  2   88  217  158   21   0  0  16  ...     0   4   3   
1                 1  0  0   11  187  210   78   5  0  13  ...     0   0   0   
2                 2  0  0    5   59  240  199   2  0   5  ...     0   0  11   
3                 3  6  0  108  255  213   13  10  0   2  ...     1   0   0   
4                 4  0  6    0   34  160    7   7  0   5  ...     0   0   0   

    58   59   60   61   62  63  digit  
0   87  228  182    0    9   2      0  
1    0  172  251  157    0  12      1  
2    0   54  173  255  138   0      2  
3  118  217  226  159    0   3      3  
4    2   42  250   51    0   4      4  

[5 rows x 66 columns]


### c- Use sklearn functions to split the dataset into testing and training sets with the following parameters:
- test_size=0.1
- random_state=2.

In [5]:
# Select features from the dataframe
# Excluding the name of the file
X = digit_df[cols[1:-1]]

# Select label from the dataframe
y = digit_df[cols[-1]]

#### Splitting the dataset

In [6]:
# Randomly splitting the original dataset into training set and testing set:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=2)

# print the size of the traning set:
print(X_train.shape)
print(y_train.shape)

# print the size of the testing set:
print(X_test.shape)
print(y_test.shape)

(1617, 64)
(1617,)
(180, 64)
(180,)


### d- Design and Train an ANN with one hidden layer with 80 neurons to recognize the digits based on the training dataset that you built in part (c).
- Use random_state=1, learning_rate_init = 0.002.
- Then, Test your ANN on testing set (from part(c)), and calculate and report the accuracy.
- Also, calculate and report the Confusion Matrix.

# ANN Classifier

In [7]:
# "my_ANN" is instantiated as an "object" of MLPClassifier "class". 
# hidden_layer_sizes: The ith element represents the number of neurons in the ith hidden layer.
# learning_rate_init: learning rate.

# 1 Hidden Layer with 80 neurons:
my_ANN = MLPClassifier(hidden_layer_sizes=(80,),
                       activation= 'logistic',
                       solver='adam', alpha=1e-5, random_state=1,
                       learning_rate_init = 0.002)

#### Training Stage: Training a predictive model using the training dataset:

In [8]:
# Training ONLY on the training set:
my_ANN.fit(X_train, y_train)

MLPClassifier(activation='logistic', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(80,), learning_rate='constant',
       learning_rate_init=0.002, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

#### Testing (Prediction) Stage: Making prediction on new observations (Testing Data) using the trained model:

In [9]:
# Testing on the testing set:
y_predict_ann = my_ANN.predict(X_test)
print(y_predict_ann)

[4 0 9 1 8 7 1 5 1 6 6 7 6 1 5 5 9 6 2 7 4 6 4 1 5 2 9 5 4 6 5 6 3 4 0 9 9
 8 4 6 8 1 5 7 9 6 9 6 1 3 0 1 9 7 3 3 1 1 8 8 9 8 5 8 7 8 3 5 8 4 3 9 3 8
 7 3 3 0 8 7 2 8 5 3 8 7 6 4 6 2 2 0 1 1 5 3 5 7 1 8 2 2 6 4 6 7 3 7 3 9 4
 7 0 3 5 1 5 0 3 9 2 7 3 2 0 8 1 9 2 1 5 9 0 3 4 3 0 8 3 2 2 7 3 1 6 7 2 8
 3 1 1 6 4 8 2 1 8 4 8 3 1 1 9 5 4 3 7 4 8 9 5 7 6 9 4 0 4 0 0 9]


#### Accuracy Evaluation:

In [10]:
# We can now compare the "predicted labels" for the Testing Set with its "actual labels" to evaluate the accuracy 

score_ann = accuracy_score(y_test, y_predict_ann)
print(score_ann)

0.911111111111


#### Confusion Matrix:

In [11]:
cm_ANN = metrics.confusion_matrix(y_test, y_predict_ann)

print("Confusion matrix:")
print(cm_ANN)

Confusion matrix:
[[13  0  0  0  1  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  1  2]
 [ 0  0 14  0  0  0  0  0  0  0]
 [ 0  0  0 22  0  0  0  0  0  0]
 [ 0  0  0  0 16  0  0  1  2  2]
 [ 0  0  0  0  0 16  0  0  0  0]
 [ 0  1  0  0  0  0 17  0  0  0]
 [ 0  0  0  0  0  0  0 17  1  0]
 [ 0  2  0  1  0  0  0  0 16  0]
 [ 0  0  0  0  0  1  0  0  1 14]]


### e- Now, use GridSearchCV to find the best number of neurons for your 1-hidden layer network.
#### Search in the range of 50-200 neurons, and use the following parameters for your NN:
- activation='logistic'
- solver='adam'
- alpha=1e-5
- random_state=1
- learning_rate_init = 0.002.

#### What is the best accuracy, and best number of neurons?

# GridSearchCV

In [12]:
# define a range for the "number of neurons" in the hidden layer for a network with 1 hidden layer:
neuron_number = [(i,) for i in range(50,200)]

# create a dictionary for grid parameter:
param_grid = dict(hidden_layer_sizes = neuron_number)
# print(param_grid,'\n')

# instantiate the model:
my_ANN = MLPClassifier(activation='logistic', solver='adam',
                       alpha=1e-5, random_state=1,
                       learning_rate_init = 0.002)

# create the grid, and define the metric for evaluating the model: 
grid = GridSearchCV(my_ANN, param_grid, cv=10, scoring='accuracy')

# fit the grid (start the grid search):
grid.fit(X, y)

# view the results:
#print(grid.cv_results_)

# view the best results corresponding to the best structure of ANN:
print('best accuracy: %f' % (grid.best_score_))
print('best number of neurons: %s' % (grid.best_params_))

best accuracy: 0.958820
best number of neurons: {'hidden_layer_sizes': (165,)}
